# reference: https://pnpm.io/pnpm-workspace_yaml

packages:
  # include all packages in direct subdirs of packages/
  - 'packages/*'

  # exclude packages that are inside test directories
  #- '!**/test/**'